/**
 * Generates src/sim/trig.ts.
 *
 * Math.sin is used HERE, at build time, and never at run time. The values are
 * committed as data, so every browser reads identical constants instead of
 * calling an implementation-approximated function. That is the whole trick.
 *
 * Run: npm run gen:trig
 */
import { writeFileSync } from 'node:fs';

const STEPS = 4096;
const table: number[] = [];
for (let i = 0; i < STEPS; i++) {
  table.push(Math.sin((i / STEPS) * Math.PI * 2));
}

const rows: string[] = [];
for (let i = 0; i < table.length; i += 4) {
  rows.push(
    '  ' +
      table
        .slice(i, i + 4)
        .map((v) => v.toExponential(17))
        .join(', ') +
      ',',
  );
}

const body = `// GENERATED by tools/gen-trig.ts - do not edit by hand.
// Values are baked constants so the simulation never calls Math.sin at run time.
// See research.md R2 and eslint.config.js.

export const TRIG_STEPS = ${STEPS};
export const TAU = ${Math.PI * 2};

const SIN: readonly number[] = [
${rows.join('\n')}
];

const wrap = (i: number): number => ((i % TRIG_STEPS) + TRIG_STEPS) % TRIG_STEPS;

/** Deterministic sine by table lookup with linear interpolation (+ - * / only). */
export function sinDet(radians: number): number {
  const scaled = (radians / TAU) * TRIG_STEPS;
  const i = Math.floor(scaled);
  const frac = scaled - i;
  const a = SIN[wrap(i)] as number;
  const b = SIN[wrap(i + 1)] as number;
  return a + (b - a) * frac;
}

/** Deterministic cosine, phase-shifted off the same table. */
export function cosDet(radians: number): number {
  return sinDet(radians + TAU / 4);
}
`;
writeFileSync(new URL('../src/sim/trig.ts', import.meta.url), body);
console.log(`wrote src/sim/trig.ts with ${STEPS} entries`);
